version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # For Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.react-app.rule=Host(`testeinternal.onlyonemp.com.br`)"
      - "traefik.http.routers.react-app.entrypoints=web"
