version: '3.8'

services:
  app_teste:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app    
    command: npm start
    deploy:
      labels:
           - "traefik.enable=true"
           #SSL
           - "traefik.http.routers.app_teste.rule=Host(`testeinternal.onlyonemp.com.br`)"
           - "traefik.http.routers.app_teste.entrypoints=web"
           - "traefik.http.services.app_teste.loadbalancer.server.port=3050"
           - "traefik.docker.network=traefik_public"
    networks:
        - traefik_public
        - agent_network

networks:
  traefik_public:
    external: true
  agent_network:
    external: true