version: '3'

services:
  app_teste:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - traefik_public
    command: npm start
    deploy:
      labels:
           - "traefik.enable=true"
           #SSL
           - "traefik.http.routers.app_teste.rule=Host(`testeinternal.onlyonemp.com.br`)"
           - "traefik.http.services.app_teste.loadbalancer.server.port=3000"
           - "traefik.http.routers.app_teste.service=app_teste"
           - "traefik.http.routers.app_teste.tls.certresolver=le"
           - "traefik.http.routers.app_teste.entrypoints=websecure"
           - "traefik.http.routers.app_teste.tls=true"
    
    
networks:
  traefik_public:
    external: true